### ISSUE TITLE
Upload started failing with an "unsuccessful execution" error

### ISSUE THREAD

**Issue by jmservera** [github/codeql-action#1316] opened 2022-10-20 11:51 UTC
I'm generating and uploading a sarif file produced by spotbugs. I started from a script into a workflow and then started packaging it [as an action](https://github.com/jmservera/spotbugs-github-action/tree/Enhance-Spotbugs-parametrization-and-sarif-output). The upload was working correctly yesterday but it started failing today without modifying anything in the action. I copy the debug output and also attach the sarif file:

```
##[debug]Evaluating condition for step: 'Upload analysis results to GitHub Security tab'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Upload analysis results to GitHub Security tab
##[debug]Loading inputs
##[debug]Evaluating: format('{0}/results.sarif', github.workspace)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> '{0}/results.sarif'
##[debug]..Evaluating Index:
##[debug]....Evaluating github:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'workspace'
##[debug]..=> '/home/runner/work/DevSecOpsWorkshop-jm/DevSecOpsWorkshop-jm'
##[debug]=> '/home/runner/work/DevSecOpsWorkshop-jm/DevSecOpsWorkshop-jm/results.sarif'
##[debug]Result: '/home/runner/work/DevSecOpsWorkshop-jm/DevSecOpsWorkshop-jm/results.sarif'
##[debug]Evaluating: github.workspace
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'workspace'
##[debug]=> '/home/runner/work/DevSecOpsWorkshop-jm/DevSecOpsWorkshop-jm'
##[debug]Result: '/home/runner/work/DevSecOpsWorkshop-jm/DevSecOpsWorkshop-jm'
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: toJson(matrix)
##[debug]Evaluating toJson:
##[debug]..Evaluating matrix:
##[debug]..=> null
##[debug]=> 'null'
##[debug]Result: 'null'
##[debug]Loading env
Run github/codeql-action/upload-sarif@v[2](https://github.com/jmenterprisedemo/DevSecOpsWorkshop-jm/actions/runs/3288903993/jobs/5420511403#step:6:2).1.28
  
##[debug]Sending status report: {"workflow_run_id":[3](https://github.com/jmenterprisedemo/DevSecOpsWorkshop-jm/actions/runs/3288903993/jobs/5420511403#step:6:3)288903993,"workflow_name":"30 SAST","job_name":"SAST-CodeQL","analysis_key":".github/workflows/sast-codeql.yml:SAST-CodeQL","commit_oid":"ec[4](https://github.com/jmenterprisedemo/DevSecOpsWorkshop-jm/actions/runs/3288903993/jobs/5420511403#step:6:4)6d2d612868f2bdfbf0bac84dbbdc00f74a6ac","ref":"refs/heads/master","action_name":"upload-sarif","action_ref":"v2.1.28","action_oid":"unknown","started_at":"2022-10-20T11:36:19.887Z","action_started_at":"2022-10-20T11:36:19.887Z","status":"starting","runner_os":"Linux","action_version":"2.1.28","matrix_vars":"null","runner_arch":"X64"}
::group::Uploading results
Uploading results
  Processing sarif files: ["/home/runner/work/DevSecOpsWorkshop-jm/DevSecOpsWorkshop-jm/results.sarif"]
  ##[debug]Unable to compute fingerprint for non-existent file: /home/runner/work/DevSecOpsWorkshop-jm/DevSecOpsWorkshop-jm/com/example/demo/controller/Controller.java
  ##[debug]Unable to compute fingerprint for non-existent file: /home/runner/work/DevSecOpsWorkshop-jm/DevSecOpsWorkshop-jm/com/example/demo/controller/Controller.java
  ##[debug]Unable to compute fingerprint for non-existent file: /home/runner/work/DevSecOpsWorkshop-jm/DevSecOpsWorkshop-jm/com/example/demo/controller/Controller.java
  ##[debug]Raw upload size: 2991 bytes
  ##[debug]Base64 zipped upload size: 1264 bytes
  ##[debug]Number of results in upload: 3
  Uploading results
  ##[debug]response status: 202
  Successfully uploaded results
  ::endgroup::
::group::Waiting for processing to finish
Waiting for processing to finish
  Analysis upload status is pending.
  ##[debug]Analysis processing is still pending...
  Analysis upload status is failed.
  Error: Code Scanning could not process the submitted SARIF file:
  unsuccessful execution, exit code: 1, description:  
  Error: Code Scanning could not process the submitted SARIF file:
  unsuccessful execution, exit code: 1, description:  
      at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/v2.1.28/lib/upload-lib.js:334:19)
      at async run (/home/runner/work/_actions/github/codeql-action/v2.1.28/lib/upload-sarif-action.js:[5](https://github.com/jmenterprisedemo/DevSecOpsWorkshop-jm/actions/runs/3288903993/jobs/5420511403#step:6:5)[6](https://github.com/jmenterprisedemo/DevSecOpsWorkshop-jm/actions/runs/3288903993/jobs/5420511403#step:6:6):13)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2.1.28/lib/upload-sarif-action.js:[7](https://github.com/jmenterprisedemo/DevSecOpsWorkshop-jm/actions/runs/3288903993/jobs/5420511403#step:6:7)1:9)
  ##[debug]Sending status report: {"workflow_run_id":32[8](https://github.com/jmenterprisedemo/DevSecOpsWorkshop-jm/actions/runs/3288903993/jobs/5420511403#step:6:8)8[9](https://github.com/jmenterprisedemo/DevSecOpsWorkshop-jm/actions/runs/3288903993/jobs/5420511403#step:6:9)03993,"workflow_name":"30 SAST","job_name":"SAST-CodeQL","analysis_key":".github/workflows/sast-codeql.yml:SAST-CodeQL","commit_oid":"ec46d2d612868f2bdfbf0bac84dbbdc00f74a6ac","ref":"refs/heads/master","action_name":"upload-sarif","action_ref":"v2.1.28","action_oid":"unknown","started_at":"2022-[10](https://github.com/jmenterprisedemo/DevSecOpsWorkshop-jm/actions/runs/3288903993/jobs/5420511403#step:6:10)-20T[11](https://github.com/jmenterprisedemo/DevSecOpsWorkshop-jm/actions/runs/3288903993/jobs/5420511403#step:6:11):36:19.887Z","action_started_at":"2022-10-20T11:36:19.887Z","status":"failure","runner_os":"Linux","action_version":"2.1.28","cause":"Code Scanning could not process the submitted SARIF file:\nunsuccessful execution, exit code: 1, description:  ","exception":"Error: Code Scanning could not process the submitted SARIF file:\nunsuccessful execution, exit code: 1, description:  \n    at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/v2.1.28/lib/upload-lib.js:334:19)\n    at async run (/home/runner/work/_actions/github/codeql-action/v2.1.28/lib/upload-sarif-action.js:56:13)\n    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2.1.28/lib/upload-sarif-action.js:71:9)","completed_at":"2022-10-20T11:36:26.504Z","matrix_vars":"null","runner_arch":"X64"}
  ##[debug]Node Action run completed with exit code 1
  ##[debug]CODEQL_ACTION_RUN_MODE='Action'
  ##[debug]CODEQL_ACTION_VERSION='2.1.28'
  ##[debug]CODEQL_ACTION_FEATURE_SARIF_COMBINE='true'
  ##[debug]CODEQL_ACTION_FEATURE_WILL_UPLOAD='true'
  ##[debug]CODEQL_ACTION_ANALYSIS_KEY='.github/workflows/sast-codeql.yml:SAST-CodeQL'
  ##[debug]CODEQL_WORKFLOW_STARTED_AT='2022-10-20T11:36:19.887Z'
  ##[debug]CODEQL_UPLOAD_SARIF__GITHUB_WORKFLOWS_SAST_CODEQL_YML_SAST_CODEQL__SPOTBUGS='CODEQL_UPLOAD_SARIF__GITHUB_WORKFLOWS_SAST_CODEQL_YML_SAST_CODEQL__SPOTBUGS'
  ##[debug]Set output sarif-id = 6b28c074-506b-11ed-9042-a31[12](https://github.com/jmenterprisedemo/DevSecOpsWorkshop-jm/actions/runs/3288903993/jobs/5420511403#step:6:12)e4fe7fb
  ##[debug]Finishing: Upload analysis results to GitHub Security tab
```

I opened the sarif file with vscode and sarif extension installed and the file looks good, it is a very simple one by now:

![image](https://user-images.githubusercontent.com/8036360/196939951-909c1538-3a1e-476f-834f-f3c6a1034f24.png)

[artifact.zip](https://github.com/github/codeql-action/files/9829350/artifact.zip)

**Comment by janisz** [comment] 2022-10-20 15:11
I have the same issue. I tried to downgrade but it did not help https://github.com/stackrox/kube-linter/pull/440

**Comment by aeisenberg** [comment] 2022-10-20 16:14
Thanks for reporting this issue. I'll investigate what the issue is and someone will get back to you.

@jmservera the artifact.zip that you uploaded is an empty file. Are you able to share the full sarif?

**Comment by jmservera** [comment] 2022-10-20 16:18
Oh, sorry, here's a new one:
[sarif.zip](https://github.com/github/codeql-action/files/9832035/sarif.zip)

**Comment by jmservera** [comment] 2022-10-20 16:21
> I have the same issue. I tried to downgrade but it did not help [stackrox/kube-linter#440](https://github.com/stackrox/kube-linter/pull/440)

I also tried to use v1 v2 and v2.1.28 and all gave the same result, I believe the problem it's into the service parsing the sarif, not in the action.

**Comment by aeisenberg** [comment] 2022-10-20 16:52
Thanks for sharing your SARIF file. I can see that the `"executionSuccessful": false` property is set. This means that even though some results were generated, there was some sort of error during execution of the tool. There was an internal change that we deployed yesterday to start treating that field as blocking code scanning from processing the results.

We are reverting the change now and you should be working again soon.

**Comment by aeisenberg** [comment] 2022-10-20 17:05
The change has been reverted and you should no longer be seeing this error. Please confirm and I will close this issue.

**Comment by jmservera** [comment] 2022-10-20 17:11
Yes, I can confirm that the issue has been solved. Thanks a lot for fixing that so fast.

**Closed** 2022-10-20 17:12 UTC
Labels: bug
