### ISSUE TITLE
Unable to upload javascript.sarif as it is not valid SARIF

### ISSUE THREAD

**Issue by olezhek85** [github/codeql-action#684] opened 2021-08-05 21:08 UTC
Unable to upload "/home/runner/work/test-repo/results/javascript.sarif" as it is not valid SARIF:
- instance.runs[0].invocations[0].toolExecutionNotifications[48].locations[0].physicalLocation.artifactLocation.uri does not conform to the "uri-reference" format
- instance.runs[0].invocations[0].toolExecutionNotifications[51].locations[0].physicalLocation.artifactLocation.uri does not conform to the "uri-reference" format
- instance.runs[0].artifacts[51].location.uri does not conform to the "uri-reference" format
- instance.runs[0].artifacts[54].location.uri does not conform to the "uri-reference" format

How to fix this issue?

**Comment by adityasharad** [comment] 2021-08-05 21:20
Thanks for reporting this. Can you share the contents of `runs[0].invocations[0].toolExecutionNotifications[48].locations[0].physicalLocation.artifactLocation.uri` from your SARIF file? 
We have observed this problem for URIs containing special characters that aren't escaped by CodeQL before putting them into the SARIF, and are working on a fix for CodeQL 2.6.0.

**Comment by olezhek85** [comment] 2021-08-05 21:23
Error details: instance.runs[0].invocations[0].toolExecutionNotifications[48].locations[0].physicalLocation.artifactLocation.uri does not conform to the "uri-reference" format
  {
    "path": [
      "runs",
      0,
      "invocations",
      0,
      "toolExecutionNotifications",
      48,
      "locations",
      0,
      "physicalLocation",
      "artifactLocation",
      "uri"
    ],
    "property": "instance.runs[0].invocations[0].toolExecutionNotifications[48].locations[0].physicalLocation.artifactLocation.uri",
    "message": "does not conform to the \"uri-reference\" format",
    "schema": {
      "description": "A string containing a valid relative or absolute URI.",
      "type": "string",
      "format": "uri-reference"
    },
    "instance": "src/core/hoсs/CustomRoute.ts",
    "name": "format",
    "argument": "uri-reference",
    "stack": "instance.runs[0].invocations[0].toolExecutionNotifications[48].locations[0].physicalLocation.artifactLocation.uri does not conform to the \"uri-reference\" format"
  }

@adityasharad, I use default SARIF file that provide Github

**Comment by adityasharad** [comment] 2021-08-05 21:48
Could you please share a link to the failing Actions run, or to your repository?

**Comment by olezhek85** [comment] 2021-08-05 21:49
The repository is private and I can provide any information

**Comment by adityasharad** [comment] 2021-08-05 21:52
Would you be able to tell us the repository name, assuming it's on GitHub.com? Then we can look up the failing upload directly.
Otherwise I'll give you instructions on how to modify your Actions workflow so that it archives the SARIF file separately, and ask you to share that file with us.

**Comment by olezhek85** [comment] 2021-08-05 21:57
Unfortunately, I cannot share repository name. Could you please provide instruction to modify actions workflow and I will provide SARIF file?

**Comment by adityasharad** [comment] 2021-08-05 22:06
- Change the `uses: github/codeql-action/analyze@v1` step in your Actions workflow to:
  ```
  - name: Perform CodeQL Analysis
    uses: github/codeql-action/analyze@v1
    with:
      upload: false  # disables the failing upload
  ```
- Add an extra step to the Actions workflow to upload the SARIF file as an Actions artifact:
  ```
  - name: Upload SARIF
    uses: actions/upload-artifact@v2
    with:
      name: sarif
      path: '../results/*.sarif'
  ```
- Start a new run of the workflow on the branch where you made these changes.
- Go to the Actions tab, click on the latest run when it completes, scroll down to Artifacts, and download the `sarif` artifact.
- Unzip it and share the contents of the `javascript.sarif` file with us. If you do not want to share the entire file, please feel free to anonymise it or share fragments of it. I am specifically interested in the field `runs[0].invocations[0].toolExecutionNotifications[48].locations[0].physicalLocation.artifactLocation.uri` that was causing the error.
  - If you have `jq` installed, one way to extract this field on the command line is
    ```
    cat javascript.sarif | jq '.runs[0].invocations[0].toolExecutionNotifications[48].locations[0].physicalLocation.artifactLocation.uri'
    ```

**Comment by olezhek85** [comment] 2021-08-05 22:20
I have got an error: 
- Error: Invalid pattern '../results/*.sarif'. Relative pathing '.' and '..' is not allowed.

I have changed to "results/*.sarif" and got the next 

Run actions/upload-artifact@v2
  with:
    name: sarif
    path: results/*.sarif
    if-no-files-found: warn
  env:
    CODEQL_ACTION_RUN_MODE: Action
    CODEQL_ACTION_VERSION: 1.0.10
    CODEQL_ACTION_FEATURE_SARIF_COMBINE: true
    CODEQL_ACTION_FEATURE_WILL_UPLOAD: true
    CODEQL_ACTION_FEATURE_MULTI_LANGUAGE: true
    CODEQL_ACTION_FEATURE_SANDWICH: true
    CODEQL_ACTION_ANALYSIS_KEY: .github/workflows/codeql-analysis.yml:analyze
    CODEQL_WORKFLOW_STARTED_AT: 2021-08-05T22:15:53.394Z
    CODEQL_RAM: 6500
Warning: No files were found with the provided path: results/*.sarif. No artifacts will be uploaded.

What should I do?

**Comment by adityasharad** [comment] 2021-08-05 22:24
Apologies, I didn't realise a relative path wasn't allowed. Can you try using the absolute path `/home/runner/work/test-repo/results/*.sarif` (replacing as appropriate with the name of your repo)?

**Comment by olezhek85** [comment] 2021-08-05 22:25
Yep, I will do it :) Wait please

**Comment by olezhek85** [comment] 2021-08-05 22:36
I run this command 
`cat javascript.sarif | jq '.runs[0].invocations[0].toolExecutionNotifications[48].locations[0].physicalLocation.artifactLocation.uri'`
And got the next 
` "src/core/hoсs/CustomRoute.ts" `

**Comment by adityasharad** [comment] 2021-08-05 23:46
Thank you. Looks like a slightly different problem: the JSON schema validation being performed by the CodeQL Action is refusing relative URIs. We're working on a fix.

**Comment by The-Compiler** [comment] 2021-08-06 09:11
FWIW I got the same issue (regarding non-ASCII characters) recently and contacted GitHub Support (#1259401). Here's what I sent them:

---

**Description**

Since yesterday, the CodeQL job on GitHub Actions fails with `Error: Unable to upload "/home/runner/work/qutebrowser/results/javascript.sarif" as it is not valid SARIF`.

Last successful build: https://github.com/qutebrowser/qutebrowser/runs/3217575109?check_suite_focus=true
First failing build: https://github.com/qutebrowser/qutebrowser/runs/3224448165?check_suite_focus=true

This seems to be connected to having a file name with umlauts in its name in the repository, see the output below.

**Reproduction Steps**

I haven't tried to find a clean reproducer, but I assume this would reproduce it:

- Create a new repository
- Activate CodeQL for Javascript files in it
- Create an `äöü.html` in the repository

**Logs**

From the build log linked above:

```
Uploading results
  Processing sarif files: ["/home/runner/work/qutebrowser/results/javascript.sarif","/home/runner/work/qutebrowser/results/python.sarif"]
Error details: instance.runs[0].invocations[0].toolExecutionNotifications[148].locations[0].physicalLocation.artifactLocation.uri does not conform to the "uri-reference" format
  {
    "path": [
      "runs",
      0,
      "invocations",
      0,
      "toolExecutionNotifications",
      148,
      "locations",
      0,
      "physicalLocation",
      "artifactLocation",
      "uri"
    ],
    "property": "instance.runs[0].invocations[0].toolExecutionNotifications[148].locations[0].physicalLocation.artifactLocation.uri",
    "message": "does not conform to the \"uri-reference\" format",
    "schema": {
      "description": "A string containing a valid relative or absolute URI.",
      "type": "string",
      "format": "uri-reference"
    },
    "instance": "tests/end2end/data/äöü.html",
    "name": "format",
    "argument": "uri-reference",
    "stack": "instance.runs[0].invocations[0].toolExecutionNotifications[148].locations[0].physicalLocation.artifactLocation.uri does not conform to the \"uri-reference\" format"
  }
Error details: instance.runs[0].artifacts[148].location.uri does not conform to the "uri-reference" format
  {
    "path": [
      "runs",
      0,
      "artifacts",
      148,
      "location",
      "uri"
    ],
    "property": "instance.runs[0].artifacts[148].location.uri",
    "message": "does not conform to the \"uri-reference\" format",
    "schema": {
      "description": "A string containing a valid relative or absolute URI.",
      "type": "string",
      "format": "uri-reference"
    },
    "instance": "tests/end2end/data/äöü.html",
    "name": "format",
    "argument": "uri-reference",
    "stack": "instance.runs[0].artifacts[148].location.uri does not conform to the \"uri-reference\" format"
  }
Error: Unable to upload "/home/runner/work/qutebrowser/results/javascript.sarif" as it is not valid SARIF:
- instance.runs[0].invocations[0].toolExecutionNotifications[148].locations[0].physicalLocation.artifactLocation.uri does not conform to the "uri-reference" format
- instance.runs[0].artifacts[148].location.uri does not conform to the "uri-reference" format
Error: Unable to upload "/home/runner/work/qutebrowser/results/javascript.sarif" as it is not valid SARIF:
- instance.runs[0].invocations[0].toolExecutionNotifications[148].locations[0].physicalLocation.artifactLocation.uri does not conform to the "uri-reference" format
- instance.runs[0].artifacts[148].location.uri does not conform to the "uri-reference" format
    at validateSarifFileSchema (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:196:15)
    at uploadFiles (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:256:9)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:132:18)
    at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze-action.js:80:27)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze-action.js:135:9)
```

**Comment by olezhek85** [comment] 2021-08-08 19:36
@adityasharad, any updates about this issue? 

I have no non-ASCII characters in my project file system and this sarif file was good before some updates I think.

**Comment by cklin** [comment] 2021-08-09 15:36
> I run this command
> `cat javascript.sarif | jq '.runs[0].invocations[0].toolExecutionNotifications[48].locations[0].physicalLocation.artifactLocation.uri'`
> And got the next
> `"src/core/hoсs/CustomRoute.ts"`

This path is non-ASCII.  The third character in `hocs` is not the ASCII character `c` but the Unicode character CYRILLIC SMALL LETTER ES `с`.

**Comment by edoardopirovano** [comment] 2021-08-11 09:32
I believe this issue should now be fixed, would you be able to run your workflow again and confirm if this is indeed the case?

**Comment by The-Compiler** [comment] 2021-08-15 12:59
I can confirm this seems to be fixed now, thank you! :+1:

**Comment by edoardopirovano** [comment] 2021-08-15 15:14
Great, thanks for checking! I'll close this issue now, do feel free to reopen it should the problem reoccur.

**Closed** 2021-08-15 15:14 UTC
