### ISSUE TITLE
Code Scanning / CodeQL: analysis considers a random branch as the Base branch of our repo instead of master

### ISSUE THREAD

**Issue by doegox** [github/codeql-action#953] opened 2022-02-27 22:38 UTC
Context: repo https://github.com/RfidResearchGroup/proxmark3 with `master` being the base branch displayed by default.

https://github.com/RfidResearchGroup/proxmark3/blob/master/.github/workflows/codeql-analysis.yml is referring to only master branch:
```
on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '30 15 * * 4'
```

And still, see the example below, result of a commit done directly to master :
![image](https://user-images.githubusercontent.com/60773/155902506-6772f1bc-e280-4c77-a523-b77a6e76f302.png)

Worrying bits are **Base branch :question:  Not found** and the line
```
Code scanning compared refs/heads/umm_wip with refs/heads/master
```
which suggests codeql-action considers the branch `umm_wip` as being the base branch instead of `master`.

( `umm_wip` is an old branch so no codeql has ever run in it )

So it sounds like a bug to me: the analysis fails to see `master` is our Base branch and this is not a PR but a simple commit to master.

**Comment by cannist** [comment] 2022-03-01 16:19
Thank you for reporting this. It has highlighted an edge case that we have not covered. 

The cause of this is that there is the PR https://github.com/RfidResearchGroup/proxmark3/pull/1188 which wants to merge `master` into `umm_wip`. We detect its existence during the upload of the analysis for master and create this extra check `Code scanning results` to present a comparison between the two branches. So far it is somewhat working as designed.

However, the PR in question is actually one we're not showing to the world because it was opened by a user we've marked as spammer. (You should get a 404 if you follow the PR link above.) So we should also not consider it when creating the check. 

This looks easy to fix. I'll update you when a fix is live.

**Comment by doegox** [comment] 2022-03-03 08:16
thank you!

**Comment by cannist** [comment] 2022-03-08 12:47
The fix is live now. You should not see the additional `Code scanning results` check appear anymore when new commits on master are analyzed. 

I'm closing this issue but please reopen it if you still see it happening.

**Comment by cannist** [comment] 2022-03-09 13:47
I just checked and the additional check is still getting created. But I think I know why.

**Comment by cannist** [comment] 2022-03-10 13:42
OK, now this should really be fixed.

**Closed by cannist** 2022-03-10 13:42 UTC
