### ISSUE TITLE
Breaking Change = New Major version

### ISSUE THREAD

**Issue by b4st1en** [github/codeql-action#1708] opened 2023-05-26 08:05 UTC
Hello,

As long as you have updated the SARIF format file, the following do not work anymore using other solutions.

Some GitHub actions rely on:

- github/codeql-action/upload-sarif@v2

And everything was fine until the v2.3.4

If there is breaking change, from my understanding, it must not keep the same Major version !

https://github.com/sysdiglabs/scan-action/issues/30

**Comment by jketema** [comment] 2023-05-26 08:41
Hi. Thanks for your report. I'm not sure if you saw https://github.com/github/codeql-action/issues/1703, but does that cover your breakage too, or do you suspect things broke for other reasons in your case?

**Comment by b4st1en** [comment] 2023-05-26 09:14
Thanks for your message, I'm still trying to work out why it doesn't work any more... at first I thought it was because of an update to the version of the SARIF format.
But unfortunately not, because Sysdig Secure already uses the latest SARIF format in their GitHuab action...

**Comment by jketema** [comment] 2023-05-26 09:27
Thanks for the update. Please let us know once you find the root cause or have any questions.

**Comment by b4st1en** [comment] 2023-05-26 10:24
Ok, the root cause was a some "Problem Exists Between Chair And Keyboard" because dev teams sound the alarm too fast... or maybe too late... or both...

It appears that the v2.3.5 already solved the issue !

Sorry for disturbance :'(

**Comment by jketema** [comment] 2023-05-26 11:05
No worries and great that you've been able to track the problem down. I'm closing this issue now, as things seem to be resolved.

**Closed by jketema** 2023-05-26 11:05 UTC
